name: 01 - Hello Actions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print greeting
        run: echo "👋 Hello from GitHub Actions!"

      - name: Show environment
        run: |
          echo "Runner OS  : $RUNNER_OS"
          echo "Repo       : $GITHUB_REPOSITORY"
          echo "Branch     : $GITHUB_REF_NAME"
          echo "Commit SHA : $GITHUB_SHA"
          echo "Triggered  : $GITHUB_EVENT_NAME"

      - name: List repo files
        run: ls -la
